services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: document_multimedia
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_backend
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/document_multimedia
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRETKEY=ew9u0fcdjmni923i6trywfocdjcbdih89q39e243200nxisaie2093eyfcd
      - DEEPGRAM_API_KEY=5598ea6698fce38fdf6dc1de45b270db815636a5
      - GROQ_API_KEY=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
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
