spring.application.name=AI-Powered-Document-Multimedia-Q-A

spring.datasource.url=jdbc:mysql://localhost:3306/document_multimedia
spring.datasource.username=root
spring.datasource.password=2830@412Ps

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=ew9u0fcdjmni923i6trywfocdjcbdih89q39e243200nxisaie2093eyfcd

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

deepgram.api.key=5598ea6698fce38fdf6dc1de45b270db815636a5
groq.api.key=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

